import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { AppHeader } from '@/components/app-header'
import { Providers } from '@/components/providers'
import { ClerkProvider } from '@clerk/nextjs'
import type { ReactNode } from 'react'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode
}>) => {
  return (
    <ClerkProvider>
      <html lang="ja">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh w-dvw`}
        >
          <Providers>
            <AppHeader />
            <main className="pt-[3rem] min-h-[calc(100dvh-3rem)] w-dvw flex items-center justify-center">
              {children}
            </main>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}

export default RootLayout
